"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.JWT_COOKIE_SAMESITE = exports.JWT_COOKIE_SECURE = exports.JWT_COOKIE_LENGTH = exports.JWT_COOKIE_NAME = exports.REMEMBER_COOKIE_SAMESITE = exports.REMEMBER_COOKIE_SECURE = exports.REMEMBER_COOKIE_LENGTH = exports.REMEMBER_COOKIE_NAME = void 0;
var REMEMBER_COOKIE_NAME = "remember-rl";
exports.REMEMBER_COOKIE_NAME = REMEMBER_COOKIE_NAME;
var REMEMBER_COOKIE_LENGTH = 7 * 24 * 60 * 60;
exports.REMEMBER_COOKIE_LENGTH = REMEMBER_COOKIE_LENGTH;
var REMEMBER_COOKIE_SECURE = null;
exports.REMEMBER_COOKIE_SECURE = REMEMBER_COOKIE_SECURE;
var REMEMBER_COOKIE_SAMESITE = "lax";
exports.REMEMBER_COOKIE_SAMESITE = REMEMBER_COOKIE_SAMESITE;
var JWT_COOKIE_NAME = "jwt-rl";
exports.JWT_COOKIE_NAME = JWT_COOKIE_NAME;
var JWT_COOKIE_LENGTH = 900;
exports.JWT_COOKIE_LENGTH = JWT_COOKIE_LENGTH;
var JWT_COOKIE_SECURE = null;
exports.JWT_COOKIE_SECURE = JWT_COOKIE_SECURE;
var JWT_COOKIE_SAMESITE = "lax";
exports.JWT_COOKIE_SAMESITE = JWT_COOKIE_SAMESITE;